CREATE TABLE [PROJEKT].[Users]
(
	PUS_Id INT IDENTITY(1,1) PRIMARY KEY,
	PUS_UserName VARCHAR(200),
	PUS_Password VARCHAR(200),
	PUS_EMAIL VARCHAR(200),
	PUS_RegistrationDate DATETIME,
	PUS_LastLogin DATETIME,
	PUS_Bio VARCHAR(500),
	PUS_Country VARCHAR(200)
)